### ISSUE TITLE
Process Container Run Method Error

### ISSUE THREAD

**Issue by ajoycekyrio** [pip-services3-python/pip-services3-container-python#1]
The process container class [ProcessContainer.py](https://github.com/pip-services3-python/pip-services3-container-python/blob/master/pip_services3_container/ProcessContainer.py)

Has a `run` method that tries to set `correlation_id` to the name of the component from the context.
It tries to use the context info class [ContextInfo.py](https://github.com/pip-services3-python/pip-services3-components-python/blob/master/pip_services3_components/info/ContextInfo.py)

However the `ProcessContainer` tries to access the property as `correlation_id = self._info.name` (Line 147 of ProcessContainer) while in the `ContextInfo` class the property is called `_name`

**Comment by afmmars** [comment]
Thanks for the feedback.
We are fixing this error.
